export const APP_FEATURE = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers dynamically generated by AI based on your target role, experience, and specific focus areas",
  },
  {
    id: "02",
    title: "AI Answer Evaluation",
    description:
      "Write and submit answers directly inside the app to receive a score out of 10, clear strengths, and detailed areas to improve from Gemini",
  },
  {
    id: "03",
    title: "Deep-Dive Explanations",
    description:
      "Click 'Learn More' on any question to request structured explanations of core concepts, coding principles, and industry best practices",
  },
  {
    id: "04",
    title: "Difficulty-Based Learning",
    description:
      "Practice interview questions categorized as Easy, Medium, and Hard to gradually build confidence and master challenging concepts",
  },
  {
    id: "05",
    title: "Conversational Follow-Ups",
    description:
      "Challenge yourself with dynamically generated follow-up questions that delve deeper into your initial responses, simulating real technical interviews",
  },
]

export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #ffe6f0 0%, #fff5f8 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #e6f0ff 0%, #f5f8ff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fef3e6 0%, #fffaf5 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f0e6ff 0%, #f8f5ff 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #e6ffe6 0%, #f5fff5 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #fff0e6 0%, #fffaf7 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #fce6ff 0%, #fef5ff 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #e6faff 0%, #f5fdff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fffde6 0%, #fffff5 100%)" },
]